### ISSUE TITLE
GIST 서버에 환경 구축

### ISSUE THREAD

**Issue by ghwlchlaks** [KOREN-Platform/Services#3]
구축 중 VNC 서버가 멈추는 에러 발생

**Comment by smartx-srkim** [comment]
구체적인 문제 상황을 서술해주시면 GIST에서 도와드릴 수 있는 방안을 찾아볼 수 있을 것 같습니다.

**Comment by ghwlchlaks** [comment]
외부 포트로 접근하여 어느 서버에 문제가 있는지 테스트해보려고 합니다. 외부포트로 접근해도 문제가 발생하면 다시 말씀드리겠습니다.
